export const PLUGIN_WINDOW_WIDTH_PX = 600;
export const PLUGIN_WINDOW_HEIGHT_PX = 450;

export const APPROX_TOKEN_COUNT_OF_CODE_GENERATION_PROMPT = 300;
export const APPROX_TOKEN_COUNT_PER_CHARACTER = 0.25;
const MAX_TOKEN_COUNT = 8192; // 8192 is the max token count for GPT-4
export const MAX_TOKEN_COUNT_FOR_CODE =
  MAX_TOKEN_COUNT - APPROX_TOKEN_COUNT_OF_CODE_GENERATION_PROMPT;
